### ISSUE TITLE
lib/binding/gdi.node missing

### ISSUE THREAD

**Issue by Xenorage** [Daninet/node-gdi#3]
in lib/GDIWindow.js 
const addon = require('./binding/gdi.node');
**This file is missing...**

{ examples } master » node ./01-simple.js                                              -- INSERT --
internal/modules/cjs/loader.js:717
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified procedure could not be found.
\\?\G:\sources\js\node\apps\node-gdi\lib\binding\gdi.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (G:\sources\js\node\apps\node-gdi\lib\GDIWindow.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)

**Comment by Daninet** [comment]
It means that the binaries were not installed. Did you have some errors when you installed the library?
What OS and Node.js version do you use?

**Comment by Xenorage** [comment]
No errors. Using win7.
Did
git clone https://github.com/Daninet/node-gdi
cd node-gdi
npm i

**Comment by Xenorage** [comment]
Hmm. 
tried 
npm install
and got gdi.node
got the same error
it was installed first time also ... probably

**Comment by Daninet** [comment]
It's not reproducible on my computer. If you say that the file is there, then it may be some OS library version interfering with the binary.

Maybe you can try to run this command in the project root:
`npx node-pre-gyp rebuild`
It will build the native bindings on your computer.
